experiment:
  name: ResNet50+FPN64
  args:
    epoch: 1000
    device: 'auto'
dataset:
  name: Gaze360
  args:
    root: '/mnt/datasets/Gaze/Gaze360'
    mode: 'frame'
dataloader:
  name: DataLoader
  args:
    batch_size: 64
    num_workers: 16
model:
  name: EEGE
  args:
optimizer:
  name: RAdam
  args:
criterion:
  name: MSELoss
  args:
evaluator:
  name: AngularError
  args:
