experiment:
  epochs: 10000
  device: 'auto'
  save: '/mnt/saves/Gaze'
dataset:
  name: Gaze360
  args:
    root: '/mnt/datasets/Gaze/Gaze360'
    mode: 'frame'
dataloader:
  name: DataLoader
  args:
    batch_size: 'auto'
    num_workers: 8
model:
  name: XiT
  args:
optimizer:
  name: RAdam
  args:
criterion:
  name: MSELoss
  args:
evalutator:
  name: AngularError
  args:
